#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
DNS切换脚本
可以在1.1.1.1和自动获取DNS之间切换
"""

import os
import subprocess
import sys
import argparse
import platform
import re


def is_admin():
    """检查是否以管理员权限运行"""
    try:
        return os.getuid() == 0
    except AttributeError:
        # Windows系统
        import ctypes
        return ctypes.windll.shell32.IsUserAnAdmin() != 0


def get_current_dns():
    """获取当前DNS设置"""
    system = platform.system().lower()
    
    if system == "windows":
        try:
            # 获取所有网络适配器
            result = subprocess.run(
                ["netsh", "interface", "show", "interface"],
                capture_output=True,
                text=True,
                encoding="utf-8"
            )
            
            # 解析输出获取启用的以太网适配器
            lines = result.stdout.split('\n')
            adapter_name = None
            
            for line in lines:
                if "已启用" in line or "Enabled" in line:
                    parts = line.split()
                    if len(parts) >= 4:
                        adapter_name = parts[3]
                        break
            
            if not adapter_name:
                print("无法找到已启用的网络适配器")
                return None
            
            # 获取DNS设置
            result = subprocess.run(
                ["netsh", "interface", "ip", "show", "dns", f"name=\"{adapter_name}\""],
                capture_output=True,
                text=True,
                encoding="utf-8"
            )
            
            dns_output = result.stdout
            if "DHCP" in dns_output or "自动" in dns_output:
                return "自动获取"
            else:
                # 提取DNS服务器
                dns_match = re.search(r"DNS 服务器.*?(\d+\.\d+\.\d+\.\d+)", dns_output)
                if dns_match:
                    return dns_match.group(1)
            
            return "未知"
        except Exception as e:
            print(f"获取DNS设置时出错: {e}")
            return None
    
    elif system == "linux":
        try:
            # 尝试从resolv.conf获取DNS
            with open("/etc/resolv.conf", "r") as f:
                content = f.read()
                
            # 检查是否是DHCP分配的
            if "# Generated by" in content:
                return "自动获取"
                
            # 提取DNS服务器
            dns_match = re.search(r"nameserver\s+(\d+\.\d+\.\d+\.\d+)", content)
            if dns_match:
                return dns_match.group(1)
                
            return "未知"
        except Exception as e:
            print(f"获取DNS设置时出错: {e}")
            return None
    
    else:
        print(f"不支持的操作系统: {system}")
        return None


def set_dns_static(dns_server="1.1.1.1"):
    """设置静态DNS"""
    system = platform.system().lower()
    
    if system == "windows":
        try:
            # 获取所有网络适配器
            result = subprocess.run(
                ["netsh", "interface", "show", "interface"],
                capture_output=True,
                text=True,
                encoding="utf-8"
            )
            
            # 解析输出获取启用的以太网适配器
            lines = result.stdout.split('\n')
            adapter_name = None
            
            for line in lines:
                if "已启用" in line or "Enabled" in line:
                    parts = line.split()
                    if len(parts) >= 4:
                        adapter_name = parts[3]
                        break
            
            if not adapter_name:
                print("无法找到已启用的网络适配器")
                return False
            
            # 设置静态DNS
            result = subprocess.run(
                ["netsh", "interface", "ip", "set", "dns", f"name=\"{adapter_name}\"", "static", dns_server, "primary"],
                capture_output=True,
                text=True,
                encoding="utf-8"
            )
            
            if result.returncode == 0:
                print(f"已将DNS设置为: {dns_server}")
                return True
            else:
                print(f"设置DNS失败: {result.stderr}")
                return False
                
        except Exception as e:
            print(f"设置DNS时出错: {e}")
            return False
    
    elif system == "linux":
        try:
            # 备份原始resolv.conf
            if os.path.exists("/etc/resolv.conf"):
                subprocess.run(["sudo", "cp", "/etc/resolv.conf", "/etc/resolv.conf.backup"], check=False)
            
            # 写入新的DNS设置
            with open("/tmp/resolv.conf", "w") as f:
                f.write(f"nameserver {dns_server}\n")
            
            # 应用新设置
            result = subprocess.run(
                ["sudo", "cp", "/tmp/resolv.conf", "/etc/resolv.conf"],
                capture_output=True,
                text=True
            )
            
            if result.returncode == 0:
                print(f"已将DNS设置为: {dns_server}")
                return True
            else:
                print(f"设置DNS失败: {result.stderr}")
                return False
                
        except Exception as e:
            print(f"设置DNS时出错: {e}")
            return False
    
    else:
        print(f"不支持的操作系统: {system}")
        return False


def set_dns_dhcp():
    """设置为自动获取DNS"""
    system = platform.system().lower()
    
    if system == "windows":
        try:
            # 获取所有网络适配器
            result = subprocess.run(
                ["netsh", "interface", "show", "interface"],
                capture_output=True,
                text=True,
                encoding="utf-8"
            )
            
            # 解析输出获取启用的以太网适配器
            lines = result.stdout.split('\n')
            adapter_name = None
            
            for line in lines:
                if "已启用" in line or "Enabled" in line:
                    parts = line.split()
                    if len(parts) >= 4:
                        adapter_name = parts[3]
                        break
            
            if not adapter_name:
                print("无法找到已启用的网络适配器")
                return False
            
            # 设置为自动获取DNS
            result = subprocess.run(
                ["netsh", "interface", "ip", "set", "dns", f"name=\"{adapter_name}\"", "dhcp"],
                capture_output=True,
                text=True,
                encoding="utf-8"
            )
            
            if result.returncode == 0:
                print("已将DNS设置为自动获取")
                return True
            else:
                print(f"设置DNS失败: {result.stderr}")
                return False
                
        except Exception as e:
            print(f"设置DNS时出错: {e}")
            return False
    
    elif system == "linux":
        try:
            # 恢复备份或使用DHCP客户端重新获取
            if os.path.exists("/etc/resolv.conf.backup"):
                result = subprocess.run(
                    ["sudo", "cp", "/etc/resolv.conf.backup", "/etc/resolv.conf"],
                    capture_output=True,
                    text=True
                )
            else:
                # 尝试使用dhclient重新获取DNS
                result = subprocess.run(
                    ["sudo", "dhclient", "-r"],
                    capture_output=True,
                    text=True
                )
                
                if result.returncode == 0:
                    result = subprocess.run(
                        ["sudo", "dhclient"],
                        capture_output=True,
                        text=True
                    )
            
            if result.returncode == 0:
                print("已将DNS设置为自动获取")
                return True
            else:
                print(f"设置DNS失败: {result.stderr}")
                return False
                
        except Exception as e:
            print(f"设置DNS时出错: {e}")
            return False
    
    else:
        print(f"不支持的操作系统: {system}")
        return False


def toggle_dns():
    """在1.1.1.1和自动获取DNS之间切换"""
    current_dns = get_current_dns()
    
    if current_dns == "自动获取":
        print("当前DNS设置为自动获取，将切换到1.1.1.1")
        return set_dns_static("1.1.1.1")
    elif current_dns == "1.1.1.1":
        print("当前DNS设置为1.1.1.1，将切换到自动获取")
        return set_dns_dhcp()
    else:
        print(f"当前DNS设置为: {current_dns}，将切换到1.1.1.1")
        return set_dns_static("1.1.1.1")


def main():
    """主函数"""
    parser = argparse.ArgumentParser(description="DNS切换工具")
    parser.add_argument("--static", action="store_true", help="设置静态DNS (1.1.1.1)")
    parser.add_argument("--dhcp", action="store_true", help="设置为自动获取DNS")
    parser.add_argument("--toggle", action="store_true", help="在1.1.1.1和自动获取DNS之间切换")
    parser.add_argument("--status", action="store_true", help="显示当前DNS设置")
    parser.add_argument("--dns", type=str, help="设置指定的DNS服务器")
    
    args = parser.parse_args()
    
    # 检查管理员权限
    if not is_admin() and platform.system().lower() == "windows":
        print("注意: 在Windows上修改DNS设置需要管理员权限")
        print("尝试以管理员权限重新运行...")
        ctypes.windll.shell32.ShellExecuteW(None, "runas", sys.executable, " ".join(sys.argv), None, 1)
        return
    
    # 显示当前DNS设置
    current_dns = get_current_dns()
    print(f"当前DNS设置: {current_dns}")
    
    # 执行相应操作
    if args.status:
        return
    elif args.static:
        set_dns_static("1.1.1.1")
    elif args.dhcp:
        set_dns_dhcp()
    elif args.toggle:
        toggle_dns()
    elif args.dns:
        set_dns_static(args.dns)
    else:
        # 默认行为：切换DNS
        toggle_dns()
    
    # 显示更新后的DNS设置
    updated_dns = get_current_dns()
    print(f"更新后DNS设置: {updated_dns}")


if __name__ == "__main__":
    main()